name: netflix_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bordered_text: ^2.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  http: ^0.13.5
  json_annotation: ^4.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner : 


flutter:
  uses-material-design: true
  assets:
    - assets/netflix_logo.png
    - assets/user_dp.png
